on:
  pull_request:
  push:
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.0'
      - run: flutter pub get
      - run: flutter test --no-sound-null-safety
      - run: flutter build apk --debug --split-per-abi --no-sound-null-safety --dart-define=production=github.ref == 'refs/heads/master'
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Push to Releases
        id: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*,build/ios/iphoneos/app.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.FLUTTER_APP_ONLY_REPO }}
          prerelease: github.ref != 'refs/heads/master'
          body: "${{ github.event.head_commit.message }}"
          allowUpdates: github.ref != 'refs/heads/master'
          name: ${{ steps.extract_branch.outputs.branch }}
      - name: Comment PR
        uses: actions/github-script@0.3.0
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.FLUTTER_APP_ONLY_REPO }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            github.issues.createComment({ issue_number, owner, repo, body: '[Baixar apk](${{ steps.release.outputs.html_url}}])' });
